oneplus2: string() is declared as private; usage of c_str() is better.
* This prevents error-messages like this

device/oneplus/oneplus2/camera/QCamera2/HAL/QCameraParameters.cpp:4814:58: error: 'string' is a private member of 'android::String8'
 4814 |         set(KEY_SUPPORTED_PREVIEW_FRAME_RATES, fpsValues.string());

Change-Id: Ib461bfa00f7313c82b9c3c6a24f5c28850aaad4d